CREATE TABLE `sap_process_order_confirmation_material_movements_data`
(     
	`Batch`                           varchar(10) NOT NULL,
	`ConfirmationGroup`               varchar(10) DEFAULT NULL,
	`ConfirmationCount`               varchar(8) DEFAULT NULL,
	`MaterialDocument`                varchar(10) DEFAULT NULL,
	`MaterialDocumentItem`            varchar(4) DEFAULT NULL,
	`MaterialDocumentYear`            varchar(4) DEFAULT NULL,
	`OrderType`                       varchar(4) DEFAULT NULL,
	`OrderID`                         varchar(14) DEFAULT NULL,
	`OrderItem`                       varchar(4) DEFAULT NULL,
	`ManufacturingOrderCategory`      varchar(2) DEFAULT NULL,
	`Material`                        varchar(40) DEFAULT NULL,
	`Plant`                           varchar(4) DEFAULT NULL,
	`Reservation`                     varchar(10) DEFAULT NULL,
	`ReservationItem`                 varchar(4) DEFAULT NULL,
	`StorageLocation`                 varchar(4) DEFAULT NULL,
	`ProductionSupplyArea`            varchar(10) DEFAULT NULL,
	`InventoryValuationType`          varchar(10) DEFAULT NULL,
	`GoodsMovementType`               varchar(3) DEFAULT NULL,
	`GoodsMovementRefDocType`         varchar(1) DEFAULT NULL,
	`InventoryUsabilityCode`          varchar(1) DEFAULT NULL,
	`InventorySpecialStockType`       varchar(1) DEFAULT NULL,
	`SalesOrder`                      varchar(10) DEFAULT NULL,
	`SalesOrderItem`                  varchar(6) DEFAULT NULL,
	`WBSElementExternalID`            varchar(24) DEFAULT NULL,
	`Supplier`                        varchar(10) DEFAULT NULL,
	`Customer`                        varchar(10) DEFAULT NULL,
	`ReservationIsFinallyIssued`      tinyint(1) DEFAULT NULL,
	`IsCompletelyDelivered`           tinyint(1) DEFAULT NULL,
	`ShelfLifeExpirationDate`         varchar(80) DEFAULT NULL,
	`ManufactureDate`                 varchar(80) DEFAULT NULL,
	`StorageType`                     varchar(3) DEFAULT NULL,
	`StorageBin`                      varchar(10) DEFAULT NULL,
	`MaterialDocumentItemText`        varchar(50) DEFAULT NULL, 
	`EntryUnit`                       varchar(3) DEFAULT NULL,
	`QuantityInEntryUnit`             varchar(15) DEFAULT NULL, 
    PRIMARY KEY (`Batch`),
    CONSTRAINT `SAPProcessOrderConfirmationMaterialMovementsData_fk` FOREIGN KEY (`OrderID`) REFERENCES `sap_process_order_confirmation_confirmation_data`(`OrderID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;